# Generated by Django 4.1.7 on 2023-03-05 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('phoneId', models.CharField(blank=True, max_length=100, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_edicion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_industria', models.TextField(blank=True, null=True)),
                ('tipo_servicio', models.TextField(blank=True, null=True)),
                ('tamaño_industria', models.TextField(blank=True, choices=[('1', 'pequeña'), ('2', 'media'), ('3', 'grande')], null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_edicion', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recetagro.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('servicios', models.TextField(blank=True, null=True)),
                ('razones', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_edicion', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recetagro.perfil')),
            ],
        ),
    ]
